### ISSUE TITLE
字幕翻译得时候我点击Submit出现下面得错误

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Dubbing#10]
![image](https://github.com/user-attachments/assets/a67b944a-b765-4809-9823-cea3bd912493)

**Comment by anstonjie** [comment]
我得配置是 
OPENAI_API_KEY = ''
OPENAI_API_BASE = 
# MODEL_NAME = 'gpt-3.5-turbo'
MODEL_NAME = 'qwen/Qwen1.5-1.8B-Chat'
# 下载模型的HF_TOKEN
HF_TOKEN = 'hf_HMqcQccdzHSgTXxxxxxxxSYUzz'

# 火山引擎
BYTEDANCE_APPID =
BYTEDANCE_ACCESS_TOKEN =

# 如果在从 huggingface 下载模型时报错，uncomment 下面的代码
HF_ENDPOINT = 'https://hf-mirror.com'
BILI_BASE64 =

**Comment by Kedreamix** [comment]
你好，你这个操作没有问题，但是有时候这个大模型的能力不足，所以有时候进行rerty几次才可能得到结果，我觉得这样的情况一般有三种解决方案
第一种是使用能力强大的大模型，比如我这里可能4B结果不好，可以用7B左右的可能会好一点
第二就是可以换openai等接口来做，我觉得这个也可以，因为chatgpt非常稳定，能得到非常好的效果
或者最后就是直接翻译，可能不需要大模型，但是速度快和稳定
