### ISSUE TITLE
進入webui 前

### ISSUE THREAD

**Issue by fatdennis** [Kedreamix/Linly-Dubbing#11]
前兩天還是可以進入webui畫面 (雖然測試時，在翻譯時已出現error)，但今天再嘗試時，已給這"translators" 禁止進入了..

(linly_dubbing) D:\Linly-Dubbing>python webui.py
C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Traceback (most recent call last):
  File "D:\Linly-Dubbing\webui.py", line 5, in <module>
    from tools.step030_translation import translate_all_transcript_under_folder
  File "D:\Linly-Dubbing\tools\step030_translation.py", line 11, in <module>
    from .step033_translation_translator import translator_response
  File "D:\Linly-Dubbing\tools\step033_translation_translator.py", line 4, in <module>
    import translators as ts
ModuleNotFoundError: No module named 'translators'

(linly_dubbing) D:\Linly-Dubbing>

**Comment by Kedreamix** [comment]
> 前兩天還是可以進入webui畫面 (雖然測試時，在翻譯時已出現error)，但今天再嘗試時，已給這"translators" 禁止進入了..
> 
> 
> 
> (linly_dubbing) D:\Linly-Dubbing>python webui.py
> 
> C:\Users\Dennis\pinokio\bin\miniconda\envs\linly_dubbing\lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
> 
>   torchaudio.set_audio_backend("soundfile")
> 
> Traceback (most recent call last):
> 
>   File "D:\Linly-Dubbing\webui.py", line 5, in <module>
> 
>     from tools.step030_translation import translate_all_transcript_under_folder
> 
>   File "D:\Linly-Dubbing\tools\step030_translation.py", line 11, in <module>
> 
>     from .step033_translation_translator import translator_response
> 
>   File "D:\Linly-Dubbing\tools\step033_translation_translator.py", line 4, in <module>
> 
>     import translators as ts
> 
> ModuleNotFoundError: No module named 'translators'
> 
> 
> 
> (linly_dubbing) D:\Linly-Dubbing>

你好，这是因为我同步更新了依赖，安装一下translators库即可，pip install translators,能够正常使用翻译功能了
