### ISSUE TITLE
使用cosyvoice 语音模型，报错failed to initialize ttsfrd resource

### ISSUE THREAD

**Issue by raulming** [Kedreamix/Linly-Dubbing#12]
在使用cosyvoice 语音模型时，报错failed to initialize ttsfrd resource，查看了cosyvoice 的源码及社区，下载了对应的ttsfrd  resource文件放到对应目录，但还是报错，然后在安装他们提供ttsfrd依赖，只能在指定py3.8的版本使用，本工程都是在3.10版本下操作的，有办法处理吗？

**Comment by Kedreamix** [comment]
你好，这个是没有问题的，在CosyVoice的REAMD中有说明，他会使用WeTextProcessing来代替

> Optionaly, you can unzip ttsfrd resouce and install ttsfrd package for better text normalization performance.
> Notice that this step is not necessary. If you do not install ttsfrd package, we will use WeTextProcessing by default.
