### ISSUE TITLE
使用 LLM 模型时可以调用远程的 Qwen2 模型吗？

### ISSUE THREAD

**Issue by fastaipod** [Kedreamix/Linly-Dubbing#14]
请问这个支持调用远程的 Qwen2 模型吗，如果支持 OPENAI_API_BASE 和 MODEL_NAME 应该怎么写？选择翻译模块是通过 OpenAI 还是 LLM ？

**Comment by Kedreamix** [comment]
可以在里面去选取模型的，暂时我没有设置Qwen2模型，因为Qwen2模型没有给出Chat版本，翻译模块在WebUI中是可以选择的，这些只是提前先配置，方便后面操作滴
