### ISSUE TITLE
这两行是不是错了？

### ISSUE THREAD

**Issue by davidxiao** [Kedreamix/Linly-Dubbing#16]
这两行， 是避免后一句overlap 前一句吗？
https://github.com/Kedreamix/Linly-Dubbing/blob/main/tools/step040_tts.py#L102-L103

是不是改为下面更合适？

```
next_start = next_line['start']
end = min(start + length, next_start)
```

**Comment by Kedreamix** [comment]
这个考虑的其实是希望结尾不要超出吧，其实这样也可以，这一部份其实因为英文和中文的长度是不同的，我觉得这两种方法一个考虑开头，一个考虑结尾，都可以其实
