### ISSUE TITLE
以后会考虑增加双语字幕翻译保留原声选项吗？

### ISSUE THREAD

**Issue by Nuclear6** [Kedreamix/Linly-Dubbing#18]
有些时候可能人们更希望听到原声，看着双语字幕，翻译后的字幕就算有声音克隆听起来还是有点小别扭，但是比CCTV6译制片的翻译听着好多了。

**Comment by Nuclear6** [comment]
我已经知道怎么修改了，并且给出双语字幕

**Comment by emourdavid** [comment]
> 我已经知道怎么修改了，并且给出双语字幕

Can you please capture screen how to do this? Thanks

**Comment by Kedreamix** [comment]
@Nuclear6 挺好的，欢迎提PR哈

**Comment by lingyunfx** [comment]
@Nuclear6  我也在尝试添加字幕为双语。但是困扰在英文字幕如何切割匹配切割后的中文字幕，可以给一个思路吗？
