### ISSUE TITLE
安装TTS模块的问题

### ISSUE THREAD

**Issue by settingtime** [Kedreamix/Linly-Dubbing#34]
有一个说法是安装coqui-tts。
但是目前transformer更新比较快，
tts/coqui-tts 中的faster-whisper 和 transformer4.42.4 安装依赖时tokenizers的版本产生了冲突，为了匹配tts/coqui-tts，我选择安装[transformer4.38.0](https://github.com/huggingface/transformers/releases/tag/v4.38.0)版本。后面顺利完成安装requirements_module
不知道这样做会不会产生别的影响冲突

**Comment by Kedreamix** [comment]
这个我觉得不能马上给你一个准确的回复，确实coqui-tts的依赖很麻烦，我的建议是可以直接安装我嵌入进仓库的版本，这个应该绝对没问题
