### ISSUE TITLE
No module named 'dora.explore'

### ISSUE THREAD

**Issue by TimesWaver** [Kedreamix/Linly-Dubbing#7]
根据使用指南操作，前面都没有问题，最后运行python webui.py报错：“(linly_dubbing) D:\Linly-Dubbing>python webui.py
Traceback (most recent call last):
  File "D:\Linly-Dubbing\webui.py", line 3, in <module>
    from tools.step010_demucs_vr import separate_all_audio_under_folder
  File "D:\Linly-Dubbing\tools\step010_demucs_vr.py", line 2, in <module>
    from demucs.api import Separator
  File "D:\Anaconda\envs\linly_dubbing\lib\site-packages\demucs\api.py", line 28, in <module>
    from dora.log import fatal
  File "D:\Anaconda\envs\linly_dubbing\lib\site-packages\dora\__init__.py", line 66, in <module>
    from .explore import Explorer, Launcher
ModuleNotFoundError: No module named 'dora.explore'”
使用‘pip install dora’和´pip install dora-search ´以及'python -m pip install dora-search'都没用

**Comment by Kedreamix** [comment]
可以参考一下 [https://github.com/facebookresearch/demucs/issues/232](https://github.com/facebookresearch/demucs/issues/232)这个

**Comment by TimesWaver** [comment]
谢谢，参考了，里面解决办法是'python -m pip install dora-search'，我用了并没有用，我其实是先尝试了这些解决办法都没用才到这里问问看的

**Comment by TimesWaver** [comment]
> 可以参考一下 [facebookresearch/demucs#232](https://github.com/facebookresearch/demucs/issues/232)这个

谢谢，参考了，里面解决办法是'python -m pip install dora-search'，我用了并没有用，我其实是先尝试了这些解决办法都没用才到这里问问看的

**Comment by Kedreamix** [comment]
那我可能暂时帮不了你，看起来我没有遇到这个问题，我感觉这个可能是bug，可以重安装环境试一下
